#pragma once

#include "card/CardRepo.h"
#include "card/LinkRepo.h"
#include "card/MilestoneRepo.h"
#include "card/TagRepo.h"
#include "git/GitOps.h"
#include "index/FtsIndexer.h"
#include "model/Card.h"
#include "model/CardLink.h"
#include "model/Milestone.h"
#include "platform/Db.h"
#include "platform/Fs.h"
#include "project/ProjectRepo.h"

#include <functional>
#include <optional>
#include <string>
#include <vector>

namespace holder::card {

// One card's worth of input to CardStore::create_batch: card_id/title/content plus outgoing
// links and milestones, in the same shape holder_backup_snapshot_page emits (see
// BACKUP_RESTORE_IMPLEMENTATION_PLAN.md step 4). card_id here is the *original* id, used only
// to resolve link targets within the batch -- create_batch assigns every restored card a fresh
// id (card_id is a global primary key, not scoped per project, so reusing the original would
// collide the moment the source project still exists on the same device; restore can't assume
// it doesn't). Links whose to_card_id isn't another card_id in the same batch are dropped
// rather than written dangling; milestone_id is generated by create_batch, not supplied here.
struct BatchCardInput {
  std::string card_id;
  std::string title;
  std::string content;
  long long created_at = 0;
  long long updated_at = 0;
  std::vector<holder::model::CardLink> links;
  std::vector<holder::model::Milestone> milestones;
};

class CardStore {
 public:
  CardStore(
      holder::platform::Db& db,
      holder::index::FtsIndexer* fts,
      holder::core::Fs* fs = nullptr,
      holder::git::GitOps* git = nullptr
  );

  void create(
      holder::model::Card card,
      const std::string& content,
      const std::optional<double>& explicit_sort_key = std::nullopt
  );

  // Writes every item as a root-level card (no parent_card_id -- batch restore is flat, no
  // hierarchy) into project_id's already-existing repo, staging every file but making exactly
  // one git commit for the whole batch, message = commit_message. project_id must already
  // exist (see BACKUP_RESTORE_IMPLEMENTATION_PLAN.md step 4: this is the bulk-write half of
  // restore; the caller creates the fresh project first via ProjectStore::create). Every card
  // gets a fresh card_id from uuid_v4 (see BatchCardInput's card_id doc comment for why); each
  // milestone likewise gets a fresh milestone_id. A link only survives if its to_card_id
  // matches another item's original card_id in the same batch, remapped to that item's new id.
  void create_batch(
      const std::string& project_id,
      const std::vector<BatchCardInput>& items,
      const std::function<std::string()>& uuid_v4,
      const std::string& commit_message
  );
  void update_content(
      const std::string& card_id,
      const std::string& content,
      const std::optional<std::string>& title,
      long long updated_at
  );
  void move(
      const std::string& card_id,
      bool has_parent_card_id,
      const std::optional<std::string>& parent_card_id,
      const std::optional<double>& sort_key,
      long long updated_at
  );
  void update_links(const std::string& card_id, long long updated_at);
  void update_milestones(const std::string& card_id, long long updated_at);
  void trash(const std::string& card_id, long long deleted_at);
  void restore(const std::string& card_id, long long updated_at);
  void hard_delete(const std::string& card_id);
  std::optional<holder::model::Card> get(const std::string& card_id) const;
  std::optional<std::string> get_content(const holder::model::Card& card);

 private:
  holder::model::Project require_project(const std::string& project_id);

  holder::platform::Db& db_;
  holder::core::Fs* fs_ = nullptr;
  holder::git::GitOps* git_ = nullptr;
  CardRepo card_repo_;
  LinkRepo link_repo_;
  MilestoneRepo milestone_repo_;
  TagRepo tag_repo_;
  holder::project::ProjectRepo project_repo_;
  holder::index::FtsIndexer* fts_ = nullptr;
};

} // namespace holder::card
